/**
 * Filters and UI state, serialized into the URL hash query.
 *
 * Everything here has a default; a param is only written to the URL when it
 * differs from that default, so a fresh visit is just "#/" and a shared link
 * carries exactly what the sharer changed.
 *
 * Params:
 *   district = csv of district slugs        (default: all)
 *   status   = csv of statuses              (default: all)
 *   mode     = csv of "ped","bike"          (default: both)
 *   years    = "2021-2024"                  (default: full range of the data)
 *   layers   = csv of "projects","crashes","schools" (default: all on)
 *   goal     = "off" hides the goal banner  (default: shown)
 *   list     = "open" opens the list drawer (default: closed on desktop)
 */
import type { District, ProjectStatus } from '../types'
import { DISTRICTS, STATUSES } from '../types'
import crashYears from '../data/crashYears.json'

export interface Filters {
  districts: District[]
  statuses: ProjectStatus[]
  modes: ('ped' | 'bike')[]
  yearMin: number
  yearMax: number
  layers: { projects: boolean; crashes: boolean; schools: boolean }
  goalDismissed: boolean
  listOpen: boolean
}

/**
 * Full crash-data year range. Generated by scripts/fetch-crashes.mjs into
 * src/data/crashYears.json, so the filter controls and captions always match
 * whatever years the committed crashes.geojson actually covers.
 */
export const YEAR_RANGE = { min: crashYears.min, max: crashYears.max }

export const DEFAULT_FILTERS: Filters = {
  districts: [...DISTRICTS],
  statuses: [...STATUSES],
  modes: ['ped', 'bike'],
  yearMin: YEAR_RANGE.min,
  yearMax: YEAR_RANGE.max,
  layers: { projects: true, crashes: true, schools: true },
  goalDismissed: false,
  listOpen: false,
}

const districtSlug = (d: District) => d.toLowerCase().replace(/\s+/g, '-')
const districtFromSlug = (s: string): District | undefined =>
  DISTRICTS.find((d) => districtSlug(d) === s)

export function readFilters(params: URLSearchParams): Filters {
  const f: Filters = structuredClone(DEFAULT_FILTERS)

  const district = params.get('district')
  if (district) {
    const parsed = district.split(',').map(districtFromSlug).filter((d): d is District => !!d)
    if (parsed.length > 0) f.districts = parsed
  }

  const status = params.get('status')
  if (status) {
    const parsed = status.split(',').filter((s): s is ProjectStatus => (STATUSES as string[]).includes(s))
    if (parsed.length > 0) f.statuses = parsed
  }

  const mode = params.get('mode')
  if (mode) {
    const parsed = mode.split(',').filter((m): m is 'ped' | 'bike' => m === 'ped' || m === 'bike')
    if (parsed.length > 0) f.modes = parsed
  }

  const years = params.get('years')
  if (years && /^\d{4}-\d{4}$/.test(years)) {
    const [a, b] = years.split('-').map(Number)
    // Clamp each ordered bound into range independently. Clamping min and max
    // separately (old approach) could invert the range for a param entirely
    // outside YEAR_RANGE (e.g. "2026-2030" → min 2026 > max 2025), hiding all
    // crashes; a range that doesn't intersect the data falls back to the full
    // range instead.
    const clamp = (n: number) => Math.min(YEAR_RANGE.max, Math.max(YEAR_RANGE.min, n))
    const lo = Math.min(a, b)
    const hi = Math.max(a, b)
    if (hi >= YEAR_RANGE.min && lo <= YEAR_RANGE.max) {
      f.yearMin = clamp(lo)
      f.yearMax = clamp(hi)
    }
  }

  const layers = params.get('layers')
  if (layers !== null) {
    const on = new Set(layers.split(','))
    f.layers = { projects: on.has('projects'), crashes: on.has('crashes'), schools: on.has('schools') }
  }

  f.goalDismissed = params.get('goal') === 'off'
  f.listOpen = params.get('list') === 'open'
  return f
}

export function writeFilters(f: Filters, base?: URLSearchParams): URLSearchParams {
  const params = new URLSearchParams(base)
  const setOrDelete = (key: string, value: string | null) => {
    if (value === null) params.delete(key)
    else params.set(key, value)
  }

  setOrDelete(
    'district',
    f.districts.length === DISTRICTS.length ? null : f.districts.map(districtSlug).join(','),
  )
  setOrDelete('status', f.statuses.length === STATUSES.length ? null : f.statuses.join(','))
  setOrDelete('mode', f.modes.length === 2 ? null : f.modes.join(','))
  setOrDelete(
    'years',
    f.yearMin === YEAR_RANGE.min && f.yearMax === YEAR_RANGE.max ? null : `${f.yearMin}-${f.yearMax}`,
  )
  const allOn = f.layers.projects && f.layers.crashes && f.layers.schools
  setOrDelete(
    'layers',
    allOn
      ? null
      : (['projects', 'crashes', 'schools'] as const).filter((k) => f.layers[k]).join(','),
  )
  setOrDelete('goal', f.goalDismissed ? 'off' : null)
  setOrDelete('list', f.listOpen ? 'open' : null)
  return params
}

export function isDefaultProjectFilters(f: Filters): boolean {
  return f.districts.length === DISTRICTS.length && f.statuses.length === STATUSES.length
}
