/**
 * Filters and UI state, serialized into the URL hash query.
 *
 * Everything here has a default; a param is only written to the URL when it
 * differs from that default, so a fresh visit is just "#/" and a shared link
 * carries exactly what the sharer changed.
 *
 * Params:
 *   district = csv of district slugs        (default: all)
 *   status   = csv of statuses              (default: all)
 *   mode     = csv of "ped","bike"          (default: both)
 *   years    = "2021-2024"                  (default: full COMPLETE-year range —
 *              see isYearPossiblyPartial(); a possibly-partial max year is
 *              excluded by default but can still be explicitly selected)
 *   sev      = csv of "fatal","injury","other" (default: all)
 *   school   = "only"                        (default: off) — school-zone crashes only
 *   light    = csv of light-condition strings (default: all)  — table only
 *   control  = a single traffic-control-type string (default: all/'')  — table only
 *   hitrun   = "only"                        (default: off)  — table only
 *   time     = csv of "overnight","morning","afternoon","evening" (default: all) — table only
 *              sev/light/control/hitrun/time have no map UI, so filtering the
 *              map by them would leave dots missing with nothing to explain it
 *              (school zone is the one exception — Task 5 puts it on both).
 *   layers   = csv of "projects","crashes","schools" (default: all on)
 *   goal     = "off" hides the goal banner  (default: shown)
 *   list     = "open" opens the list drawer (default: closed on desktop)
 */
import type { District, ProjectStatus, TimeBand } from '../types'
import { DISTRICTS, STATUSES } from '../types'
import crashYears from '../data/crashYears.json'

export type CrashSeverity = 'fatal' | 'injury' | 'other'

export const SEVERITIES: CrashSeverity[] = ['fatal', 'injury', 'other']

/** Plain-language severity labels — severity must always be readable as text,
 *  never conveyed by colour alone. */
export const SEVERITY_LABEL: Record<CrashSeverity, string> = {
  fatal: 'A person was killed',
  injury: 'At least one person injured',
  other: 'No injuries recorded',
}

/**
 * VDOT's light-condition categories, verified against all 976 Henrico
 * ped/bike records 2017-2026 (fixed regulatory vocabulary — DMV crash-report
 * categories don't change often, same reasoning as hardcoding the KABCO
 * severity scale above). Numeric prefixes ("4. ") are stripped by
 * scripts/fetch-crashes.mjs before the data ever reaches the site.
 */
export const LIGHT_CONDITIONS = [
  'Daylight',
  'Dawn',
  'Dusk',
  'Darkness - Road Lighted',
  'Darkness - Road Not Lighted',
  'Darkness - Unknown Road Lighting',
] as const

export const TIME_BANDS: TimeBand[] = ['overnight', 'morning', 'afternoon', 'evening']

export const TIME_BAND_LABEL: Record<TimeBand, string> = {
  overnight: 'Overnight (12am–6am)',
  morning: 'Morning (6am–12pm)',
  afternoon: 'Afternoon (12pm–6pm)',
  evening: 'Evening (6pm–12am)',
}

export interface Filters {
  districts: District[]
  statuses: ProjectStatus[]
  modes: ('ped' | 'bike')[]
  yearMin: number
  yearMax: number
  severities: CrashSeverity[]
  /** Map + table (Task 5: the only crash sub-filter that belongs on both). */
  schoolZoneOnly: boolean
  /** Table only. */
  lights: string[]
  /** Table only. '' = all traffic-control types. */
  trafficControl: string
  /** Table only. */
  hitRunOnly: boolean
  /** Table only. */
  timeBands: TimeBand[]
  layers: { projects: boolean; crashes: boolean; schools: boolean }
  goalDismissed: boolean
  listOpen: boolean
}

/**
 * Full crash-data year range. Generated by scripts/fetch-crashes.mjs into
 * src/data/crashYears.json, so the filter controls and captions always match
 * whatever years the committed crashes.geojson actually covers.
 */
export const YEAR_RANGE = { min: crashYears.min, max: crashYears.max }

/** Latest individual crash date in the committed data (Eastern-correct ISO
 *  date), for the "runs through {date}" caveat everywhere 2026 appears. */
export const LATEST_CRASH_DATE: string = crashYears.latestDate

/**
 * Is `year` possibly still incomplete? True exactly when it equals the
 * VIEWER's current calendar year — computed live, not baked into the fetched
 * data, so the caveat correctly stops appearing on its own once real time
 * moves past that year (no re-fetch required, no stale flag to forget about).
 */
export function isYearPossiblyPartial(year: number): boolean {
  return year === new Date().getFullYear()
}

/**
 * Default upper bound for filters: the newest COMPLETE year. If the data's
 * max year is possibly still filling in, it's excluded from the default
 * (Task 1) but stays selectable — the year dropdowns and #/crashes still
 * offer it, just don't show it until asked for.
 */
const DEFAULT_YEAR_MAX = isYearPossiblyPartial(YEAR_RANGE.max)
  ? Math.max(YEAR_RANGE.min, YEAR_RANGE.max - 1)
  : YEAR_RANGE.max

/**
 * Viewport width below which this counts as a phone-sized screen. Matches
 * the 760px breakpoint the stylesheet already uses to switch the map UI
 * from floating desktop panels to the mobile bottom sheet.
 */
const NARROW_VIEWPORT_PX = 760

/**
 * Captured once, at module load, rather than read per call.
 *
 * A "default" is a decision made when the page opens; re-deriving it on
 * every read would mean rotating a phone silently changed what the
 * defaults *are* mid-session, which could flip a layer the visitor never
 * touched. Sampling once keeps defaults stable for the life of the tab —
 * an explicit `layers` param, and any toggle the visitor flips, still
 * always wins over it.
 */
const OPENED_ON_NARROW_VIEWPORT =
  typeof window !== 'undefined' && window.innerWidth < NARROW_VIEWPORT_PX

/**
 * Default layer visibility.
 *
 * Schools default OFF on phone-sized screens: 68 extra marks are useful
 * when you are examining one neighbourhood, but at the county-wide view a
 * phone opens on they are context for context, crowding out the projects
 * this site is actually about. The toggle stays in the same place in the
 * Layers section for everyone — this changes the starting state, not what
 * is available.
 */
export function defaultLayers(): Filters['layers'] {
  return { projects: true, crashes: true, schools: !OPENED_ON_NARROW_VIEWPORT }
}

export const DEFAULT_FILTERS: Filters = {
  districts: [...DISTRICTS],
  statuses: [...STATUSES],
  modes: ['ped', 'bike'],
  yearMin: YEAR_RANGE.min,
  yearMax: DEFAULT_YEAR_MAX,
  severities: [...SEVERITIES],
  schoolZoneOnly: false,
  lights: [...LIGHT_CONDITIONS],
  trafficControl: '',
  hitRunOnly: false,
  timeBands: [...TIME_BANDS],
  layers: defaultLayers(),
  goalDismissed: false,
  listOpen: false,
}

const districtSlug = (d: District) => d.toLowerCase().replace(/\s+/g, '-')
const districtFromSlug = (s: string): District | undefined =>
  DISTRICTS.find((d) => districtSlug(d) === s)

export function readFilters(params: URLSearchParams): Filters {
  const f: Filters = structuredClone(DEFAULT_FILTERS)

  const district = params.get('district')
  if (district) {
    const parsed = district.split(',').map(districtFromSlug).filter((d): d is District => !!d)
    if (parsed.length > 0) f.districts = parsed
  }

  const status = params.get('status')
  if (status) {
    const parsed = status.split(',').filter((s): s is ProjectStatus => (STATUSES as string[]).includes(s))
    if (parsed.length > 0) f.statuses = parsed
  }

  const mode = params.get('mode')
  if (mode) {
    const parsed = mode.split(',').filter((m): m is 'ped' | 'bike' => m === 'ped' || m === 'bike')
    if (parsed.length > 0) f.modes = parsed
  }

  const sev = params.get('sev')
  if (sev) {
    const parsed = sev.split(',').filter((s): s is CrashSeverity => (SEVERITIES as string[]).includes(s))
    if (parsed.length > 0) f.severities = parsed
  }

  const light = params.get('light')
  if (light) {
    const parsed = light.split(',').filter((l) => (LIGHT_CONDITIONS as readonly string[]).includes(l))
    if (parsed.length > 0) f.lights = parsed
  }

  const control = params.get('control')
  if (control) f.trafficControl = control

  const time = params.get('time')
  if (time) {
    const parsed = time.split(',').filter((t): t is TimeBand => (TIME_BANDS as string[]).includes(t))
    if (parsed.length > 0) f.timeBands = parsed
  }

  f.schoolZoneOnly = params.get('school') === 'only'
  f.hitRunOnly = params.get('hitrun') === 'only'

  const years = params.get('years')
  if (years && /^\d{4}-\d{4}$/.test(years)) {
    const [a, b] = years.split('-').map(Number)
    // Clamp each ordered bound into range independently. Clamping min and max
    // separately (old approach) could invert the range for a param entirely
    // outside YEAR_RANGE (e.g. "2026-2030" → min 2026 > max 2025), hiding all
    // crashes; a range that doesn't intersect the data falls back to the full
    // range instead.
    const clamp = (n: number) => Math.min(YEAR_RANGE.max, Math.max(YEAR_RANGE.min, n))
    const lo = Math.min(a, b)
    const hi = Math.max(a, b)
    if (hi >= YEAR_RANGE.min && lo <= YEAR_RANGE.max) {
      f.yearMin = clamp(lo)
      f.yearMax = clamp(hi)
    }
  }

  const layers = params.get('layers')
  if (layers !== null) {
    const on = new Set(layers.split(','))
    f.layers = { projects: on.has('projects'), crashes: on.has('crashes'), schools: on.has('schools') }
  }

  f.goalDismissed = params.get('goal') === 'off'
  f.listOpen = params.get('list') === 'open'
  return f
}

export function writeFilters(f: Filters, base?: URLSearchParams): URLSearchParams {
  const params = new URLSearchParams(base)
  const setOrDelete = (key: string, value: string | null) => {
    if (value === null) params.delete(key)
    else params.set(key, value)
  }

  setOrDelete(
    'district',
    f.districts.length === DISTRICTS.length ? null : f.districts.map(districtSlug).join(','),
  )
  setOrDelete('status', f.statuses.length === STATUSES.length ? null : f.statuses.join(','))
  setOrDelete('mode', f.modes.length === 2 ? null : f.modes.join(','))
  setOrDelete(
    'sev',
    f.severities.length === SEVERITIES.length ? null : f.severities.join(','),
  )
  setOrDelete(
    'light',
    f.lights.length === LIGHT_CONDITIONS.length ? null : f.lights.join(','),
  )
  setOrDelete('control', f.trafficControl === '' ? null : f.trafficControl)
  setOrDelete(
    'time',
    f.timeBands.length === TIME_BANDS.length ? null : f.timeBands.join(','),
  )
  setOrDelete('school', f.schoolZoneOnly ? 'only' : null)
  setOrDelete('hitrun', f.hitRunOnly ? 'only' : null)
  setOrDelete(
    'years',
    f.yearMin === YEAR_RANGE.min && f.yearMax === DEFAULT_YEAR_MAX ? null : `${f.yearMin}-${f.yearMax}`,
  )
  // Compared against defaultLayers(), not against "all three on", so the
  // param stays absent whenever the visitor is simply sitting on the
  // defaults for their screen — otherwise every phone visit would
  // immediately rewrite its own URL to ?layers=projects,crashes purely
  // because Schools starts off there.
  const layerDefaults = defaultLayers()
  const layersAreDefault = (['projects', 'crashes', 'schools'] as const).every(
    (k) => f.layers[k] === layerDefaults[k],
  )
  setOrDelete(
    'layers',
    layersAreDefault
      ? null
      : (['projects', 'crashes', 'schools'] as const).filter((k) => f.layers[k]).join(','),
  )
  setOrDelete('goal', f.goalDismissed ? 'off' : null)
  setOrDelete('list', f.listOpen ? 'open' : null)
  return params
}

export function isDefaultProjectFilters(f: Filters): boolean {
  return f.districts.length === DISTRICTS.length && f.statuses.length === STATUSES.length
}
