/**
 * The map. MapLibre GL over OpenFreeMap's Positron style (free for
 * production use, no API key; muted and light so the data layers dominate).
 *
 * VISUAL HIERARCHY — projects are the subject, crashes are context:
 *  - Projects render largest and topmost: a paper-colored casing (cuts a
 *    clean channel through the basemap) under an ink casing (holds status
 *    colors to 3:1+ contrast on light ground) under the status-color line or
 *    point itself. Placeholder lines draw dashed, placeholder points draw
 *    hollow — examples must look provisional, never mistaken for real.
 *  - Crashes render smallest and beneath projects: small dots, opacity/size
 *    receding at county-wide zoom and firming up as you zoom into a
 *    neighborhood. People walking are filled circles, people biking are
 *    rings (shape, not color, separates them); fatal crashes are larger with
 *    a dark outline. Rendered respectfully: no icons, no gamification,
 *    minimal popover copy.
 *  - Schools: small neutral squares, name on click/tap.
 *  - A quiet Henrico County outline frames all of it; every custom layer is
 *    inserted via LAYER_ORDER so the stacking above is a structural
 *    invariant, not something that depends on data-load timing.
 *
 * This component is lazy-loaded so document pages never pay for MapLibre.
 * If WebGL is unavailable the parent never mounts this — the project list
 * and detail pages work fully without a map.
 */
import { useEffect, useRef } from 'react'
import maplibregl from 'maplibre-gl'
import 'maplibre-gl/dist/maplibre-gl.css'
import type {
  ExpressionSpecification,
  GeoJSONSource,
  LayerSpecification,
  Map as MLMap,
  MapMouseEvent,
} from 'maplibre-gl'
import type { Project } from '../types'
import { geometryPoints } from '../data/projects'
import henricoBounds from '../data/henricoBounds.json'
import type { Filters } from '../lib/urlState'
import type { CrashCollection } from '../lib/useGeoData'
import { navigate } from '../lib/router'

const STYLE_URL = 'https://tiles.openfreemap.org/styles/positron'

// Free fallback basemap (MapLibre's own demotiles) used only if the primary
// style fails to load. Low detail, but it keeps the project/crash/school data
// on a real map instead of a blank rectangle.
const FALLBACK_STYLE = 'https://demotiles.maplibre.org/style.json'

/**
 * Henrico County's real bounds (generated by scripts/fetch-boundary.mjs from
 * the same Census TIGERweb polygon rendered as the outline layer below — the
 * initial camera and the outline can never drift out of sync). Used for the
 * initial `fitBounds` and, padded, for `maxBounds`.
 */
const COUNTY_BOUNDS: [[number, number], [number, number]] = [
  [henricoBounds.minLng, henricoBounds.minLat],
  [henricoBounds.maxLng, henricoBounds.maxLat],
]

/** Generous pan limit: county bounds padded ~45%, enough to see Richmond and
 *  neighboring counties for orientation, not so much a visitor can wander off
 *  to another state. */
function paddedMaxBounds(): [[number, number], [number, number]] {
  const [[minLng, minLat], [maxLng, maxLat]] = COUNTY_BOUNDS
  const padLng = (maxLng - minLng) * 0.45
  const padLat = (maxLat - minLat) * 0.45
  return [
    [minLng - padLng, minLat - padLat],
    [maxLng + padLng, maxLat + padLat],
  ]
}

const COLORS = {
  ink: '#16181d',
  inkSoft: '#4a5158',
  paper: '#fafbfc',
  crash: '#b3261e',
  yellow: '#f5b700', // sign-yellow accent — school-zone crash halo only
  announced: '#0072b2',
  design: '#56b4e9',
  construction: '#e69f00',
  complete: '#009e73',
}

const STATUS_COLOR: ExpressionSpecification = [
  'match',
  ['get', 'status'],
  'announced',
  COLORS.announced,
  'design',
  COLORS.design,
  'construction',
  COLORS.construction,
  'complete',
  COLORS.complete,
  COLORS.ink,
]

/**
 * Fixed bottom-to-top stacking for every custom layer this app adds, as a
 * structural invariant independent of load order. Crashes/schools load
 * async and may finish before OR after the project layers exist; without
 * this, whichever loads second would simply paint on top (which is exactly
 * how crashes ended up visually dominating projects before this fix).
 */
const LAYER_ORDER = [
  'henrico-mask-fill',
  'henrico-boundary-line',
  'crash-schoolzone-halo',
  'crash-fatal-halo',
  'crash-ped',
  'crash-bike',
  'schools',
  'project-sel-line',
  'project-sel-point',
  'project-line-casing',
  'project-line-casing-paper',
  'project-point-casing',
  'project-lines',
  'project-lines-placeholder',
  'project-points',
  'project-points-placeholder',
] as const

/** Add a layer at its correct position in LAYER_ORDER, regardless of what
 *  else has been added yet (safe to call in any order, any number of times
 *  across a style swap). */
function addLayerOrdered(map: MLMap, layer: LayerSpecification) {
  if (map.getLayer(layer.id)) return
  const idx = LAYER_ORDER.indexOf(layer.id as (typeof LAYER_ORDER)[number])
  let beforeId: string | undefined
  if (idx >= 0) {
    for (let i = idx + 1; i < LAYER_ORDER.length; i++) {
      if (map.getLayer(LAYER_ORDER[i])) {
        beforeId = LAYER_ORDER[i]
        break
      }
    }
  }
  map.addLayer(layer, beforeId)
}

/** projects.json → GeoJSON (lines for segments, points for single spots). */
function projectsToGeoJSON(projects: Project[]): GeoJSON.FeatureCollection {
  return {
    type: 'FeatureCollection',
    features: projects.map((p) => {
      const pts = geometryPoints(p)
      return {
        type: 'Feature',
        geometry:
          pts.length > 1
            ? { type: 'LineString', coordinates: pts }
            : { type: 'Point', coordinates: pts[0] },
        properties: { id: p.id, status: p.status, placeholder: p.placeholder, name: p.name },
      }
    }),
  }
}

/**
 * Builds the "spotlight" mask: a world-covering rectangle with the county
 * polygon cut out as a hole, so filling it dims everything outside Henrico.
 * Ring winding is forced explicitly (RFC 7946: exterior CCW, holes CW)
 * rather than assumed from the source data, so this is correct even if a
 * future boundary source ships opposite-wound rings.
 */
function ringSignedArea(ring: [number, number][]): number {
  let area = 0
  for (let i = 0; i < ring.length - 1; i++) {
    area += ring[i][0] * ring[i + 1][1] - ring[i + 1][0] * ring[i][1]
  }
  return area
}

function withOrientation(ring: [number, number][], wantCCW: boolean): [number, number][] {
  const isCCW = ringSignedArea(ring) > 0
  return isCCW === wantCCW ? ring : [...ring].reverse()
}

function buildMaskGeometry(boundary: GeoJSON.FeatureCollection): GeoJSON.Feature | null {
  const county = boundary.features[0]?.geometry
  if (!county || county.type !== 'Polygon') return null
  const countyRing = county.coordinates[0] as [number, number][]
  const worldRing: [number, number][] = [
    [-180, -85],
    [180, -85],
    [180, 85],
    [-180, 85],
    [-180, -85],
  ]
  return {
    type: 'Feature',
    properties: {},
    geometry: {
      type: 'Polygon',
      coordinates: [withOrientation(worldRing, true), withOrientation(countyRing, false)],
    },
  }
}

/** A small rounded-square icon for schools, drawn pixel-by-pixel. */
function schoolIcon(): { width: number; height: number; data: Uint8Array } {
  const size = 14
  const data = new Uint8Array(size * size * 4)
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const i = (y * size + x) * 4
      const edge = Math.min(x, y, size - 1 - x, size - 1 - y)
      const corner = Math.min(x, size - 1 - x) + Math.min(y, size - 1 - y)
      if (corner < 2) continue // clipped corners stay transparent
      if (edge < 2) {
        // white border so the square reads on any basemap color
        data[i] = data[i + 1] = data[i + 2] = data[i + 3] = 255
      } else {
        // slate fill #5f6b76
        data[i] = 0x5f
        data[i + 1] = 0x6b
        data[i + 2] = 0x76
        data[i + 3] = 255
      }
    }
  }
  return { width: size, height: size, data }
}

/** Escape text before it goes into popup HTML — data is never trusted markup. */
function esc(value: unknown): string {
  return String(value).replace(
    /[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!,
  )
}

/** Neutral, factual popover copy for a crash point. */
function crashPopupHTML(props: Record<string, unknown>): string {
  const mode =
    props.mode === 'both'
      ? 'people walking and biking'
      : props.mode === 'bike'
        ? 'a person biking'
        : 'a person walking'
  const sev =
    props.sev === 'fatal'
      ? 'A person was killed.'
      : props.sev === 'injury'
        ? 'At least one person was injured.'
        : 'No injuries were recorded.'
  return (
    `<div class="sw-popup"><p class="sw-popup__kicker">Reported crash · ${esc(Number(props.year))}</p>` +
    `<p>Involving ${mode}. ${sev}</p></div>`
  )
}

/**
 * Radius (CSS px) of the box queried when a keyboard user presses Enter.
 *
 * This MUST be >= the crosshair graphic's visual half-extent (17px — see
 * .map-crosshair, 34px square). The original 16px was smaller than the very
 * reticle that advertises it, so a dot sitting visually under the crosshair's
 * arm could fall outside the hit box; at county-wide zoom (2.5px dots) the box
 * landed between dots entirely, which is why Enter appeared to do nothing at
 * every position tried. Slightly larger than the graphic = forgiving, and
 * never "looks targeted but isn't".
 */
const KEYBOARD_HIT_RADIUS = 22

/** Max features listed in a single popup before we stop enumerating. */
const MAX_LISTED_FEATURES = 6

/**
 * Stable identity for a rendered feature, used to dedupe. One real-world
 * thing can come back several times from queryRenderedFeatures because we
 * deliberately make casing layers clickable too (a project line matches
 * `project-line-casing-paper` AND `project-lines`), and because tiles repeat
 * features at their seams. Without this, "1 project" would report as "3
 * features here".
 */
function featureKey(f: maplibregl.MapGeoJSONFeature): string {
  if (f.layer.id.startsWith('project-')) return `project:${f.properties.id}`
  const g = f.geometry
  const coords = g.type === 'Point' ? (g.coordinates as number[]).join(',') : ''
  if (f.layer.id === 'schools') return `school:${f.properties.name}:${coords}`
  return `crash:${coords}:${f.properties.year}:${f.properties.mode}:${f.properties.sev}`
}

function dedupeFeatures(features: maplibregl.MapGeoJSONFeature[]): maplibregl.MapGeoJSONFeature[] {
  const seen = new Set<string>()
  const out: maplibregl.MapGeoJSONFeature[] = []
  for (const f of features) {
    const k = featureKey(f)
    if (seen.has(k)) continue
    seen.add(k)
    out.push(f)
  }
  return out
}

/** One-line, neutral description of a feature for the multi-feature list. */
function featureSummary(f: maplibregl.MapGeoJSONFeature): string {
  if (f.layer.id.startsWith('project-')) {
    return `<a href="#/project/${esc(f.properties.id)}">${esc(f.properties.name)}</a>`
  }
  if (f.layer.id === 'schools') return `${esc(f.properties.name)} (school)`
  const p = f.properties
  const mode =
    p.mode === 'both'
      ? 'people walking and biking'
      : p.mode === 'bike'
        ? 'a person biking'
        : 'a person walking'
  const sev = p.sev === 'fatal' ? 'a person was killed' : p.sev === 'injury' ? 'someone was injured' : 'no injuries recorded'
  return `Reported crash, ${esc(Number(p.year))} — ${mode}, ${sev}`
}

/**
 * Popup listing several overlapping features. Shown instead of silently
 * picking one, so a keyboard user is never given an arbitrary subset of
 * what is under their cursor.
 */
function multiFeaturePopupHTML(features: maplibregl.MapGeoJSONFeature[]): string {
  const shown = features.slice(0, MAX_LISTED_FEATURES)
  const items = shown.map((f) => `<li>${featureSummary(f)}</li>`).join('')
  const extra = features.length - shown.length
  const more = extra > 0 ? `<p class="sw-popup__more">and ${extra} more — zoom in to separate them</p>` : ''
  return (
    `<div class="sw-popup"><p class="sw-popup__kicker">${features.length} features here</p>` +
    `<ul class="sw-popup__list">${items}</ul>${more}</div>`
  )
}

/**
 * Which crash modes each layer shows, given the mode filter.
 * "both" crashes involve a walker AND a biker, so they appear as a filled
 * dot while walkers are shown, and as a ring when only bikers are shown.
 */
function modeSets(f: Filters): { ped: string[]; bike: string[] } {
  const wantPed = f.modes.includes('ped')
  const wantBike = f.modes.includes('bike')
  return {
    ped: wantPed ? ['ped', 'both'] : [],
    bike: wantBike ? (wantPed ? ['bike'] : ['bike', 'both']) : [],
  }
}

function yearAndMode(f: Filters, modes: string[]): ExpressionSpecification {
  const modeExpr: ExpressionSpecification =
    modes.length === 0
      ? ['boolean', false]
      : ['match', ['get', 'mode'], modes, true, false]
  const clauses: ExpressionSpecification[] = [
    ['>=', ['get', 'year'], f.yearMin],
    ['<=', ['get', 'year'], f.yearMax],
    modeExpr,
  ]
  // School zone is the one crash sub-filter that lives on the map too
  // (Task 5) — every other one (severity, light, traffic control, hit-run,
  // time band) is table-only, same reasoning as the `sev` URL param.
  if (f.schoolZoneOnly) clauses.push(['==', ['get', 'schoolZone'], true])
  return ['all', ...clauses]
}

/** Crash size: recedes at county-wide zoom, firms up in a neighborhood. */
function crashRadius(fatalBoost: number, base: [number, number]): ExpressionSpecification {
  const [lo, hi] = base
  return [
    'interpolate',
    ['linear'],
    ['zoom'],
    9,
    ['case', ['==', ['get', 'sev'], 'fatal'], lo + fatalBoost, lo],
    15,
    ['case', ['==', ['get', 'sev'], 'fatal'], hi + fatalBoost, hi],
  ]
}

const CRASH_OPACITY: ExpressionSpecification = [
  'interpolate',
  ['linear'],
  ['zoom'],
  9,
  0.4,
  15,
  0.75,
]

interface Props {
  projects: Project[] // already filtered by district/status
  crashes: CrashCollection | null
  schools: GeoJSON.FeatureCollection | null
  boundary: GeoJSON.FeatureCollection | null
  filters: Filters
  selected: Project | null
  onMapFailed: () => void
}

export default function MapView({
  projects,
  crashes,
  schools,
  boundary,
  filters,
  selected,
  onMapFailed,
}: Props) {
  const containerRef = useRef<HTMLDivElement>(null)
  const mapRef = useRef<MLMap | null>(null)
  const loadedRef = useRef(false)
  // Lets the data/filter effect re-check what's under the keyboard crosshair
  // after layers change, without reaching into the map effect's closure.
  const crosshairRefreshRef = useRef<(() => void) | null>(null)

  // Latest props, reachable from map event handlers without re-binding them.
  const stateRef = useRef({ projects, crashes, schools, boundary, filters, selected })
  stateRef.current = { projects, crashes, schools, boundary, filters, selected }

  /** Push current data + filters into the map. Safe to call repeatedly. */
  function sync(map: MLMap) {
    const { projects, crashes, schools, boundary, filters, selected } = stateRef.current

    const projSrc = map.getSource('projects') as GeoJSONSource | undefined
    if (projSrc) projSrc.setData(projectsToGeoJSON(projects))

    if (boundary && !map.getSource('henrico-boundary')) {
      map.addSource('henrico-boundary', { type: 'geojson', data: boundary })
      const mask = buildMaskGeometry(boundary)
      if (mask) map.addSource('henrico-mask', { type: 'geojson', data: mask as GeoJSON.Feature })
      addBoundaryLayers(map)
    }
    if (crashes && !map.getSource('crashes')) {
      map.addSource('crashes', { type: 'geojson', data: crashes as GeoJSON.FeatureCollection })
      addCrashLayers(map)
    }
    if (schools && !map.getSource('schools')) {
      map.addSource('schools', { type: 'geojson', data: schools })
      addSchoolLayer(map)
    }

    const vis = (on: boolean) => (on ? 'visible' : 'none')
    const projectLayers = [
      'project-sel-line',
      'project-sel-point',
      'project-line-casing',
      'project-line-casing-paper',
      'project-point-casing',
      'project-lines',
      'project-lines-placeholder',
      'project-points',
      'project-points-placeholder',
    ]
    for (const id of projectLayers)
      if (map.getLayer(id)) map.setLayoutProperty(id, 'visibility', vis(filters.layers.projects))
    for (const id of ['crash-schoolzone-halo', 'crash-fatal-halo', 'crash-ped', 'crash-bike'])
      if (map.getLayer(id)) map.setLayoutProperty(id, 'visibility', vis(filters.layers.crashes))
    if (map.getLayer('schools'))
      map.setLayoutProperty('schools', 'visibility', vis(filters.layers.schools))

    const sets = modeSets(filters)
    if (map.getLayer('crash-ped')) map.setFilter('crash-ped', yearAndMode(filters, sets.ped))
    if (map.getLayer('crash-bike')) map.setFilter('crash-bike', yearAndMode(filters, sets.bike))
    if (map.getLayer('crash-fatal-halo')) {
      const anyShown = [...new Set([...sets.ped, ...sets.bike])]
      map.setFilter('crash-fatal-halo', [
        'all',
        ['==', ['get', 'sev'], 'fatal'],
        yearAndMode(filters, anyShown),
      ])
    }
    if (map.getLayer('crash-schoolzone-halo')) {
      const anyShown = [...new Set([...sets.ped, ...sets.bike])]
      // Not gated on filters.schoolZoneOnly — this halo IS the "which of the
      // visible crashes are school-zone" signal, so it needs to render
      // whether or not the isolate-only checkbox is on (when it is, every
      // visible crash is school-zone and the halo is simply on every dot).
      map.setFilter('crash-schoolzone-halo', [
        'all',
        ['==', ['get', 'schoolZone'], true],
        yearAndMode({ ...filters, schoolZoneOnly: false }, anyShown),
      ])
    }

    const selId = selected?.id ?? ''
    if (map.getLayer('project-sel-line')) map.setFilter('project-sel-line', ['all', ['==', ['geometry-type'], 'LineString'], ['==', ['get', 'id'], selId]])
    if (map.getLayer('project-sel-point')) map.setFilter('project-sel-point', ['all', ['==', ['geometry-type'], 'Point'], ['==', ['get', 'id'], selId]])
  }

  function addBoundaryLayers(map: MLMap) {
    if (map.getSource('henrico-mask')) {
      // Subtle: evaluated by eye, not asserted as "correct" — see MapView's
      // usage notes / the build report for how this was judged.
      addLayerOrdered(map, {
        id: 'henrico-mask-fill',
        type: 'fill',
        source: 'henrico-mask',
        paint: { 'fill-color': COLORS.ink, 'fill-opacity': 0.1 },
      })
    }
    addLayerOrdered(map, {
      id: 'henrico-boundary-line',
      type: 'line',
      source: 'henrico-boundary',
      layout: { 'line-join': 'round' },
      paint: { 'line-color': COLORS.inkSoft, 'line-width': 1.5, 'line-opacity': 0.55 },
    })
  }

  function addProjectLayers(map: MLMap) {
    map.addSource('projects', {
      type: 'geojson',
      data: projectsToGeoJSON(stateRef.current.projects),
    })

    // ink halo under the selected project — reads as "this one is chosen"
    addLayerOrdered(map, {
      id: 'project-sel-line',
      type: 'line',
      source: 'projects',
      filter: ['==', ['get', 'id'], ''],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: { 'line-color': COLORS.ink, 'line-width': 16, 'line-opacity': 0.9 },
    })
    addLayerOrdered(map, {
      id: 'project-sel-point',
      type: 'circle',
      source: 'projects',
      filter: ['==', ['get', 'id'], ''],
      paint: { 'circle-radius': 18, 'circle-color': COLORS.ink, 'circle-opacity': 0.9 },
    })

    // Casing stack for EVERY project line: ink (holds status colors to 3:1+
    // contrast on the light basemap) under paper (cuts a clean channel
    // through basemap clutter so the color reads as the subject, not
    // fighting with roads/labels underneath it).
    addLayerOrdered(map, {
      id: 'project-line-casing',
      type: 'line',
      source: 'projects',
      filter: ['==', ['geometry-type'], 'LineString'],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: { 'line-color': COLORS.ink, 'line-width': 10, 'line-opacity': 0.85 },
    })
    addLayerOrdered(map, {
      id: 'project-line-casing-paper',
      type: 'line',
      source: 'projects',
      filter: ['==', ['geometry-type'], 'LineString'],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: { 'line-color': COLORS.paper, 'line-width': 8, 'line-opacity': 0.95 },
    })
    addLayerOrdered(map, {
      id: 'project-point-casing',
      type: 'circle',
      source: 'projects',
      filter: ['==', ['geometry-type'], 'Point'],
      paint: { 'circle-radius': 12, 'circle-color': COLORS.paper, 'circle-opacity': 0.95 },
    })

    // real projects: solid line — placeholders: dashed (dasharray can't be
    // data-driven in MapLibre, hence two layers)
    addLayerOrdered(map, {
      id: 'project-lines',
      type: 'line',
      source: 'projects',
      filter: ['all', ['==', ['geometry-type'], 'LineString'], ['!=', ['get', 'placeholder'], true]],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: { 'line-color': STATUS_COLOR, 'line-width': 6 },
    })
    addLayerOrdered(map, {
      id: 'project-lines-placeholder',
      type: 'line',
      source: 'projects',
      filter: ['all', ['==', ['geometry-type'], 'LineString'], ['==', ['get', 'placeholder'], true]],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: { 'line-color': STATUS_COLOR, 'line-width': 6, 'line-dasharray': [1.8, 1.4] },
    })

    // verified points: solid status fill with an ink edge (contrast + "real")
    addLayerOrdered(map, {
      id: 'project-points',
      type: 'circle',
      source: 'projects',
      filter: ['all', ['==', ['geometry-type'], 'Point'], ['!=', ['get', 'placeholder'], true]],
      paint: {
        'circle-radius': 9,
        'circle-color': STATUS_COLOR,
        'circle-stroke-color': COLORS.ink,
        'circle-stroke-width': 2,
      },
    })
    // placeholder points: hollow ring — provisional, never mistaken for real,
    // mirroring the dashed treatment of placeholder lines
    addLayerOrdered(map, {
      id: 'project-points-placeholder',
      type: 'circle',
      source: 'projects',
      filter: ['all', ['==', ['geometry-type'], 'Point'], ['==', ['get', 'placeholder'], true]],
      paint: {
        'circle-radius': 9,
        'circle-color': COLORS.paper,
        'circle-stroke-color': STATUS_COLOR,
        'circle-stroke-width': 3,
      },
    })
  }

  function addCrashLayers(map: MLMap) {
    // Sign-yellow outer ring marking school-zone crashes (Task 5: the
    // site's exact subject, 38 of 976 records 2017-2026 — surfaced with a
    // filter AND this permanent visual marker, since a legend entry with no
    // persistent encoding to explain wouldn't mean much; still just a
    // categorical highlight, no rate/breakdown drawn from it). Drawn wider
    // than the fatal halo so the two nest visibly on a crash that is both.
    addLayerOrdered(map, {
      id: 'crash-schoolzone-halo',
      type: 'circle',
      source: 'crashes',
      filter: ['==', ['get', 'schoolZone'], true],
      paint: {
        'circle-radius': ['interpolate', ['linear'], ['zoom'], 9, 7.5, 15, 12],
        'circle-color': 'rgba(0,0,0,0)',
        'circle-stroke-color': COLORS.yellow,
        'circle-stroke-width': ['interpolate', ['linear'], ['zoom'], 9, 1.6, 15, 2.4],
        'circle-stroke-opacity': ['interpolate', ['linear'], ['zoom'], 9, 0.55, 15, 0.95],
      },
    })
    // dark outline that marks fatal crashes, drawn under the dot itself.
    // Sized/opacity recede at county-wide zoom, firm up in a neighborhood —
    // crashes are context here, not the subject; see MapView's file header.
    addLayerOrdered(map, {
      id: 'crash-fatal-halo',
      type: 'circle',
      source: 'crashes',
      filter: ['==', ['get', 'sev'], 'fatal'],
      paint: {
        'circle-radius': ['interpolate', ['linear'], ['zoom'], 9, 5.5, 15, 9],
        'circle-color': 'rgba(0,0,0,0)',
        'circle-stroke-color': COLORS.ink,
        'circle-stroke-width': ['interpolate', ['linear'], ['zoom'], 9, 1.2, 15, 2],
        'circle-stroke-opacity': ['interpolate', ['linear'], ['zoom'], 9, 0.45, 15, 0.85],
      },
    })
    addLayerOrdered(map, {
      id: 'crash-ped',
      type: 'circle',
      source: 'crashes',
      filter: ['match', ['get', 'mode'], ['ped', 'both'], true, false],
      paint: {
        'circle-radius': crashRadius(2, [2.5, 4.5]),
        'circle-color': COLORS.crash,
        'circle-opacity': CRASH_OPACITY,
        'circle-stroke-color': '#ffffff',
        'circle-stroke-width': 1,
        'circle-stroke-opacity': CRASH_OPACITY,
      },
    })
    addLayerOrdered(map, {
      id: 'crash-bike',
      type: 'circle',
      source: 'crashes',
      filter: ['match', ['get', 'mode'], ['bike'], true, false],
      paint: {
        // a ring: transparent center, red stroke
        'circle-radius': crashRadius(1.5, [2.5, 4.5]),
        'circle-color': 'rgba(0,0,0,0)',
        'circle-stroke-color': COLORS.crash,
        'circle-stroke-width': ['interpolate', ['linear'], ['zoom'], 9, 1.4, 15, 2.2],
        'circle-stroke-opacity': CRASH_OPACITY,
      },
    })
  }

  function addSchoolLayer(map: MLMap) {
    if (!map.hasImage('school-square')) map.addImage('school-square', schoolIcon())
    addLayerOrdered(map, {
      id: 'schools',
      type: 'symbol',
      source: 'schools',
      layout: { 'icon-image': 'school-square', 'icon-size': 1, 'icon-allow-overlap': true },
    })
  }

  // ----- map lifecycle (once) -----
  useEffect(() => {
    if (!containerRef.current || mapRef.current) return

    // Opt-in only: enables reading the WebGL drawing buffer for
    // scripts/verify-map.mjs. Off for every real visitor (small perf cost),
    // on only when that script navigates with ?verifyMap=1.
    const verifyMap =
      typeof window !== 'undefined' && new URLSearchParams(window.location.search).get('verifyMap') === '1'

    let map: MLMap
    try {
      map = new maplibregl.Map({
        container: containerRef.current,
        style: STYLE_URL,
        bounds: COUNTY_BOUNDS,
        fitBoundsOptions: { padding: 24 },
        maxBounds: paddedMaxBounds(),
        attributionControl: { compact: false },
        ...(verifyMap ? { canvasContextAttributes: { preserveDrawingBuffer: true } } : {}),
      })
    } catch {
      onMapFailed()
      return
    }
    mapRef.current = map
    if (import.meta.env.DEV) {
      // dev-only handle for debugging in the browser console
      ;(window as unknown as Record<string, unknown>).__swMap = map
    }

    map.addControl(new maplibregl.NavigationControl({ showCompass: false }), 'bottom-right')

    // The canvas is keyboard-focusable and pannable, but arrow-key panning is
    // captured by screen-reader browse/scan modes (confirmed with Windows
    // Narrator; true of NVDA and JAWS by default too) before the canvas ever
    // sees the keypress — expected AT behavior, not a bug here. So the
    // accessible NAME stays short, and the longer instructions + the pointer
    // to the real text alternative live in a separate DESCRIPTION, wired via
    // aria-describedby to actual DOM text rather than folded into one long
    // aria-label string. This also keeps the skip-map link (rendered by
    // HomePage, just before this component mounts) and this description
    // saying the same thing through one shared source of truth would be
    // nice, but they serve different moments (skip link: before you even
    // reach the map; description: after you're on it and want to know why
    // panning isn't working) so both are worth stating in full.
    const canvas = map.getCanvas()
    canvas.setAttribute(
      'aria-label',
      'Interactive map of pedestrian-safety projects and reported crashes in Henrico County',
    )
    const description = document.createElement('div')
    description.id = 'sw-map-description'
    description.className = 'visually-hidden'
    description.textContent =
      'Pan with the arrow keys; press Enter to inspect the feature at the center crosshair. ' +
      'All projects are also listed in the project list. For a full text version of the crash ' +
      'data, see the crash data table.'
    map.getContainer().appendChild(description)
    canvas.setAttribute('aria-describedby', description.id)
    canvas.setAttribute('role', 'application')

    // Center crosshair: the keyboard "cursor". Shown ONLY when the canvas has
    // real keyboard focus (:focus-visible) — NOT on a mouse click, which
    // MapLibre also focuses the canvas for (to enable keyboard nav right
    // after a click). Checking :focus-visible inside the 'focus' handler
    // uses the browser's own keyboard-vs-pointer heuristic instead of a
    // hand-rolled one, so it stays correct across input methods.
    const crosshair = document.createElement('div')
    crosshair.className = 'map-crosshair'
    crosshair.setAttribute('aria-hidden', 'true')
    // centre dot: the second (non-colour) channel of the "armed" signal
    const crosshairDot = document.createElement('span')
    crosshairDot.className = 'map-crosshair__dot'
    crosshair.appendChild(crosshairDot)
    map.getContainer().appendChild(crosshair)

    // Politely announces what's under the crosshair, so a screen-reader user
    // gets the same "Enter will do something" signal the sighted keyboard user
    // gets from the crosshair turning yellow. Updated only when the map
    // settles, never mid-pan, to avoid chatter.
    const liveRegion = document.createElement('div')
    liveRegion.className = 'visually-hidden'
    liveRegion.setAttribute('aria-live', 'polite')
    map.getContainer().appendChild(liveRegion)

    // Debounce timer for the SR announcement only — see announceArmedState()
    // below for why this is debounced while the visual armed-state is not.
    let announceTimer: number | null = null
    const cancelPendingAnnouncement = () => {
      if (announceTimer !== null) {
        window.clearTimeout(announceTimer)
        announceTimer = null
      }
    }

    canvas.addEventListener('focus', () => {
      if (canvas.matches(':focus-visible')) {
        crosshair.classList.add('map-crosshair--on')
        refreshArmedVisual()
        announceArmedState()
      }
    })
    canvas.addEventListener('blur', () => {
      crosshair.classList.remove('map-crosshair--on')
      crosshair.classList.remove('map-crosshair--armed')
      liveRegion.textContent = ''
      cancelPendingAnnouncement()
    })

    // ---- Layers: (re)installed for whichever basemap style is active.
    // setStyle() (the fallback path) wipes custom sources/layers, so this must
    // be safe to run again after a style swap; the getSource guard makes it
    // idempotent within a single style.
    const installLayers = (m: MLMap) => {
      if (m.getSource('projects')) return
      addProjectLayers(m)
      sync(m)
    }

    // ---- Interactions: bound to the map, not the style, so attach once.
    // Casing layers are included so the effective click/tap target is wider
    // than just the narrow color line/point — useful on mobile.
    const interactive = [
      'project-lines',
      'project-lines-placeholder',
      'project-line-casing-paper',
      'project-points',
      'project-points-placeholder',
      'project-point-casing',
      'crash-ped',
      'crash-bike',
      'schools',
    ]
    for (const layer of interactive) {
      map.on('mouseenter', layer, () => (map.getCanvas().style.cursor = 'pointer'))
      map.on('mouseleave', layer, () => (map.getCanvas().style.cursor = ''))
    }

    /**
     * The popup currently on screen, if any. Tracked as an instance (not
     * looked up in the DOM) because MapLibre closes popups on Escape itself:
     * by the time a DOM-querying handler runs, the element is already gone and
     * focus has fallen to <body>. Holding the instance lets us own the whole
     * lifecycle and always hand focus back to the map.
     */
    let activePopup: maplibregl.Popup | null = null

    /** Return focus to the map so closing a popup never strands the user on <body>. */
    const refocusMap = () => map.getCanvas().focus()

    /** Open a popup, replacing any current one. `fromKeyboard` makes it take
     *  focus and hand focus back to the map when it closes. */
    const openPopup = (
      html: string,
      lngLat: maplibregl.LngLatLike,
      fromKeyboard: boolean,
      offset = 8,
    ) => {
      activePopup?.remove()
      const popup = new maplibregl.Popup({ offset, focusAfterOpen: fromKeyboard })
        .setLngLat(lngLat)
        .setHTML(html)
      popup.on('close', () => {
        if (activePopup === popup) activePopup = null
        // Only reclaim focus for keyboard users — doing it after a mouse
        // dismissal would yank focus around unexpectedly.
        if (fromKeyboard) refocusMap()
      })
      popup.addTo(map)
      activePopup = popup
    }

    /**
     * Act on a feature: navigate for a project, or open a popup for a
     * crash/school. `moveFocus` is set for keyboard activation so the popup
     * receives focus (screen-reader users hear it; Escape/Tab work).
     */
    const activateFeature = (
      f: maplibregl.MapGeoJSONFeature,
      lngLat: maplibregl.LngLatLike,
      moveFocus: boolean,
    ) => {
      if (f.layer.id.startsWith('project-')) {
        navigate(`/project/${f.properties.id}`)
        return
      }
      openPopup(
        f.layer.id === 'schools'
          ? `<div class="sw-popup"><p class="sw-popup__kicker">School</p><p>${esc(f.properties.name)}</p></div>`
          : crashPopupHTML(f.properties),
        lngLat,
        moveFocus,
        f.layer.id === 'schools' ? 10 : 8,
      )
    }

    const present = () => interactive.filter((l) => map.getLayer(l))

    map.on('click', (e: MapMouseEvent) => {
      const f = map.queryRenderedFeatures(e.point, { layers: present() })[0]
      if (f) activateFeature(f, e.lngLat, false)
    })

    /** Everything under the crosshair, deduped. Shared by the armed-state
     *  indicator and the Enter handler so what you see is exactly what you get. */
    const featuresAtCrosshair = (): maplibregl.MapGeoJSONFeature[] => {
      const layers = present()
      if (layers.length === 0) return []
      const rect = map.getContainer().getBoundingClientRect()
      const cx = rect.width / 2
      const cy = rect.height / 2
      const r = KEYBOARD_HIT_RADIUS
      const box: [maplibregl.PointLike, maplibregl.PointLike] = [
        [cx - r, cy - r],
        [cx + r, cy + r],
      ]
      return dedupeFeatures(map.queryRenderedFeatures(box, { layers }))
    }

    const describeFeatureCount = (n: number): string =>
      n === 0
        ? 'Nothing at crosshair'
        : n === 1
          ? '1 feature at crosshair. Press Enter to inspect.'
          : `${n} features at crosshair. Press Enter to list them.`

    /**
     * Reflect "Enter will do something here" in the crosshair itself, so a
     * keyboard user never has to press it blindly to find out. Only runs while
     * the crosshair is visible (keyboard focus), so mouse users pay nothing.
     * Synchronous and unthrottled — this visual feedback has to be instant for
     * sighted keyboard users, who this interaction is designed for.
     */
    function refreshArmedVisual() {
      if (!crosshair.classList.contains('map-crosshair--on')) return
      const found = featuresAtCrosshair()
      crosshair.classList.toggle('map-crosshair--armed', found.length > 0)
    }

    /**
     * Screen-reader announcement of what's under the crosshair — debounced,
     * unlike the visual state above.
     *
     * Most screen-reader users never reach this at all: arrow-key panning is
     * captured by the AT's own browse/scan mode before the map's handler sees
     * it (confirmed with Narrator; true of NVDA/JAWS by default), so for that
     * majority the live region would only ever fire once, on focus — their
     * real path to this data is #/crashes, now signposted by the skip-map
     * link and this canvas's aria-describedby. But a smaller group pairs a
     * screen reader with sighted keyboard use, or has toggled a focus/forms
     * mode that passes keys through, and DOES reach here — for them,
     * announcing on every intermediate 'moveend' is actively harmful: holding
     * an arrow key repeats it many times a second, each firing its own
     * moveend, which queues overlapping "N features..." announcements that
     * cut each other off mid-sentence. A settle debounce fires once, after
     * motion genuinely stops, which is how a live region is meant to behave.
     * We debounce the announcement only, never refreshArmedVisual() above —
     * degrading the sighted keyboard user's instant visual feedback to fix
     * a screen-reader edge case would be its own regression.
     */
    function announceArmedState() {
      cancelPendingAnnouncement()
      announceTimer = window.setTimeout(() => {
        announceTimer = null
        if (!crosshair.classList.contains('map-crosshair--on')) return
        liveRegion.textContent = describeFeatureCount(featuresAtCrosshair().length)
      }, 600)
    }

    // Keep the indicator honest as the user pans/zooms, and after any filter
    // or data change (sync() can add/remove layers under the crosshair).
    map.on('move', refreshArmedVisual)
    map.on('moveend', () => {
      refreshArmedVisual()
      announceArmedState()
    })
    map.on('idle', refreshArmedVisual)
    crosshairRefreshRef.current = refreshArmedVisual

    // Keyboard activation: Enter/Space inspects whatever is under the center
    // crosshair. Multiple overlapping features are listed rather than silently
    // resolved to an arbitrary one.
    map.getCanvas().addEventListener('keydown', (ev: KeyboardEvent) => {
      if (ev.key !== 'Enter' && ev.key !== ' ') return
      const found = featuresAtCrosshair()
      if (found.length === 0) {
        // Say so immediately — this is a direct reply to a deliberate
        // keypress, not ambient pan chatter, so it bypasses the debounce.
        // Cancel any pending debounced update too, so it can't land a moment
        // later and silently overwrite this answer with stale information.
        cancelPendingAnnouncement()
        liveRegion.textContent = describeFeatureCount(0)
        return
      }
      ev.preventDefault()
      if (found.length === 1) {
        activateFeature(found[0], map.getCenter(), true)
        return
      }
      openPopup(multiFeaturePopupHTML(found), map.getCenter(), true)
    })

    // Escape closes an open popup and puts focus back on the map. Capture
    // phase + stopPropagation so this doesn't also trigger the project detail
    // panel's own Escape-to-close handler. Acting on the tracked instance
    // (rather than a DOM lookup) means the popup's own 'close' handler runs,
    // which is what restores focus.
    map.getContainer().addEventListener(
      'keydown',
      (ev: KeyboardEvent) => {
        if (ev.key !== 'Escape' || !activePopup) return
        ev.stopPropagation()
        ev.preventDefault()
        activePopup.remove()
      },
      true,
    )

    // ---- Basemap resilience. The map must never sit as a silent blank: if the
    // primary style never loads, retry once with the free demotiles style; if
    // that also fails, surface the on-voice fallback panel (onMapFailed). Data
    // layers are re-installed over whichever style ends up loading.
    let styleState: 'primary' | 'fallback' | 'failed' = 'primary'
    const alive = () => mapRef.current === map // guard stale timers after unmount

    const markLoaded = () => {
      loadedRef.current = true
      installLayers(map)
    }
    const giveUp = (reason: string) => {
      if (styleState === 'failed' || !alive()) return
      styleState = 'failed'
      console.error('[SafeWalk] Basemap unavailable:', reason)
      onMapFailed()
    }
    const goFallback = (reason: string) => {
      if (styleState !== 'primary' || !alive()) return
      styleState = 'fallback'
      console.warn('[SafeWalk] Primary basemap failed, retrying with fallback:', reason)
      map.once('style.load', markLoaded)
      window.setTimeout(() => {
        if (alive() && styleState === 'fallback' && !map.isStyleLoaded()) giveUp('fallback timeout')
      }, 8000)
      try {
        map.setStyle(FALLBACK_STYLE)
      } catch (err) {
        giveUp(String(err))
      }
    }

    map.on('load', () => {
      if (styleState === 'primary') markLoaded()
    })
    map.on('error', (e) => {
      // Only errors BEFORE a style has loaded mean "no basemap". Once a style
      // is up, stray tile errors are harmless and must not trigger a failover.
      if (alive() && !map.isStyleLoaded()) goFallback(String(e?.error?.message ?? 'map error'))
    })
    // Watchdog: some failures (DNS, hang) never emit an error event.
    window.setTimeout(() => {
      if (alive() && styleState === 'primary' && !map.isStyleLoaded()) goFallback('primary timeout')
    }, 8000)

    return () => {
      // map.remove() tears down MapLibre's own DOM (canvas, controls) but not
      // elements we appended ourselves — without this, React StrictMode's
      // dev-only double-invoke of this effect leaves an orphaned crosshair
      // <div> behind on every mount (harmless in production, where effects
      // run once, but real DOM debt in dev regardless).
      crosshair.remove()
      liveRegion.remove()
      description.remove()
      if (announceTimer !== null) window.clearTimeout(announceTimer)
      crosshairRefreshRef.current = null
      map.remove()
      mapRef.current = null
      loadedRef.current = false
    }
    // The map is created exactly once; prop changes flow through sync().
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // ----- react to data / filter changes -----
  useEffect(() => {
    const map = mapRef.current
    if (map && loadedRef.current) {
      sync(map)
      // Toggling a layer off can remove whatever the crosshair was armed on.
      crosshairRefreshRef.current?.()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projects, crashes, schools, boundary, filters, selected])

  // ----- auto-zoom to the selected project -----
  useEffect(() => {
    const map = mapRef.current
    if (!map || !selected) return
    const pts = geometryPoints(selected)
    const desktop = window.matchMedia('(min-width: 760px)').matches
    const padding = desktop
      ? { top: 80, left: 80, bottom: 80, right: 460 } // clear the detail panel
      : { top: 60, left: 40, right: 40, bottom: Math.round(window.innerHeight * 0.55) }
    if (pts.length === 1) {
      map.easeTo({ center: pts[0], zoom: Math.max(map.getZoom(), 14), padding, duration: 500 })
    } else {
      const bounds = pts.reduce((b, p) => b.extend(p), new maplibregl.LngLatBounds(pts[0], pts[0]))
      map.fitBounds(bounds, { padding, maxZoom: 15, duration: 500 })
    }
  }, [selected])

  return <div ref={containerRef} className="map-canvas" data-testid="map" />
}
