/**
 * The map. MapLibre GL over OpenFreeMap's Positron style (free for
 * production use, no API key; muted and light so the data layers dominate).
 *
 * VISUAL HIERARCHY — projects are the subject, crashes are context:
 *  - Projects render largest and topmost: a paper-colored casing (cuts a
 *    clean channel through the basemap) under an ink casing (holds status
 *    colors to 3:1+ contrast on light ground) under the status-color line or
 *    point itself. Placeholder lines draw dashed, placeholder points draw
 *    hollow — examples must look provisional, never mistaken for real.
 *  - Crashes render smallest and beneath projects: small dots, opacity/size
 *    receding at county-wide zoom and firming up as you zoom into a
 *    neighborhood. People walking are filled circles, people biking are
 *    rings (shape, not color, separates them); fatal crashes are larger with
 *    a dark outline. Rendered respectfully: no icons, no gamification,
 *    minimal popover copy.
 *  - Schools: small neutral squares, name on click/tap.
 *  - A quiet Henrico County outline frames all of it; every custom layer is
 *    inserted via LAYER_ORDER so the stacking above is a structural
 *    invariant, not something that depends on data-load timing.
 *
 * This component is lazy-loaded so document pages never pay for MapLibre.
 * If WebGL is unavailable the parent never mounts this — the project list
 * and detail pages work fully without a map.
 */
import { useEffect, useRef } from 'react'
import maplibregl from 'maplibre-gl'
import 'maplibre-gl/dist/maplibre-gl.css'
import type {
  ExpressionSpecification,
  GeoJSONSource,
  LayerSpecification,
  Map as MLMap,
  MapMouseEvent,
} from 'maplibre-gl'
import type { Project } from '../types'
import { geometryPoints } from '../data/projects'
import henricoBounds from '../data/henricoBounds.json'
import type { Filters } from '../lib/urlState'
import type { CrashCollection } from '../lib/useGeoData'
import { navigate } from '../lib/router'

const STYLE_URL = 'https://tiles.openfreemap.org/styles/positron'

// Free fallback basemap (MapLibre's own demotiles) used only if the primary
// style fails to load. Low detail, but it keeps the project/crash/school data
// on a real map instead of a blank rectangle.
const FALLBACK_STYLE = 'https://demotiles.maplibre.org/style.json'

/**
 * Henrico County's real bounds (generated by scripts/fetch-boundary.mjs from
 * the same Census TIGERweb polygon rendered as the outline layer below — the
 * initial camera and the outline can never drift out of sync). Used for the
 * initial `fitBounds` and, padded, for `maxBounds`.
 */
const COUNTY_BOUNDS: [[number, number], [number, number]] = [
  [henricoBounds.minLng, henricoBounds.minLat],
  [henricoBounds.maxLng, henricoBounds.maxLat],
]

/** Generous pan limit: county bounds padded ~45%, enough to see Richmond and
 *  neighboring counties for orientation, not so much a visitor can wander off
 *  to another state. */
function paddedMaxBounds(): [[number, number], [number, number]] {
  const [[minLng, minLat], [maxLng, maxLat]] = COUNTY_BOUNDS
  const padLng = (maxLng - minLng) * 0.45
  const padLat = (maxLat - minLat) * 0.45
  return [
    [minLng - padLng, minLat - padLat],
    [maxLng + padLng, maxLat + padLat],
  ]
}

const COLORS = {
  ink: '#16181d',
  inkSoft: '#4a5158',
  paper: '#fafbfc',
  crash: '#b3261e',
  announced: '#0072b2',
  design: '#56b4e9',
  construction: '#e69f00',
  complete: '#009e73',
}

const STATUS_COLOR: ExpressionSpecification = [
  'match',
  ['get', 'status'],
  'announced',
  COLORS.announced,
  'design',
  COLORS.design,
  'construction',
  COLORS.construction,
  'complete',
  COLORS.complete,
  COLORS.ink,
]

/**
 * Fixed bottom-to-top stacking for every custom layer this app adds, as a
 * structural invariant independent of load order. Crashes/schools load
 * async and may finish before OR after the project layers exist; without
 * this, whichever loads second would simply paint on top (which is exactly
 * how crashes ended up visually dominating projects before this fix).
 */
const LAYER_ORDER = [
  'henrico-mask-fill',
  'henrico-boundary-line',
  'crash-fatal-halo',
  'crash-ped',
  'crash-bike',
  'schools',
  'project-sel-line',
  'project-sel-point',
  'project-line-casing',
  'project-line-casing-paper',
  'project-point-casing',
  'project-lines',
  'project-lines-placeholder',
  'project-points',
  'project-points-placeholder',
] as const

/** Add a layer at its correct position in LAYER_ORDER, regardless of what
 *  else has been added yet (safe to call in any order, any number of times
 *  across a style swap). */
function addLayerOrdered(map: MLMap, layer: LayerSpecification) {
  if (map.getLayer(layer.id)) return
  const idx = LAYER_ORDER.indexOf(layer.id as (typeof LAYER_ORDER)[number])
  let beforeId: string | undefined
  if (idx >= 0) {
    for (let i = idx + 1; i < LAYER_ORDER.length; i++) {
      if (map.getLayer(LAYER_ORDER[i])) {
        beforeId = LAYER_ORDER[i]
        break
      }
    }
  }
  map.addLayer(layer, beforeId)
}

/** projects.json → GeoJSON (lines for segments, points for single spots). */
function projectsToGeoJSON(projects: Project[]): GeoJSON.FeatureCollection {
  return {
    type: 'FeatureCollection',
    features: projects.map((p) => {
      const pts = geometryPoints(p)
      return {
        type: 'Feature',
        geometry:
          pts.length > 1
            ? { type: 'LineString', coordinates: pts }
            : { type: 'Point', coordinates: pts[0] },
        properties: { id: p.id, status: p.status, placeholder: p.placeholder, name: p.name },
      }
    }),
  }
}

/**
 * Builds the "spotlight" mask: a world-covering rectangle with the county
 * polygon cut out as a hole, so filling it dims everything outside Henrico.
 * Ring winding is forced explicitly (RFC 7946: exterior CCW, holes CW)
 * rather than assumed from the source data, so this is correct even if a
 * future boundary source ships opposite-wound rings.
 */
function ringSignedArea(ring: [number, number][]): number {
  let area = 0
  for (let i = 0; i < ring.length - 1; i++) {
    area += ring[i][0] * ring[i + 1][1] - ring[i + 1][0] * ring[i][1]
  }
  return area
}

function withOrientation(ring: [number, number][], wantCCW: boolean): [number, number][] {
  const isCCW = ringSignedArea(ring) > 0
  return isCCW === wantCCW ? ring : [...ring].reverse()
}

function buildMaskGeometry(boundary: GeoJSON.FeatureCollection): GeoJSON.Feature | null {
  const county = boundary.features[0]?.geometry
  if (!county || county.type !== 'Polygon') return null
  const countyRing = county.coordinates[0] as [number, number][]
  const worldRing: [number, number][] = [
    [-180, -85],
    [180, -85],
    [180, 85],
    [-180, 85],
    [-180, -85],
  ]
  return {
    type: 'Feature',
    properties: {},
    geometry: {
      type: 'Polygon',
      coordinates: [withOrientation(worldRing, true), withOrientation(countyRing, false)],
    },
  }
}

/** A small rounded-square icon for schools, drawn pixel-by-pixel. */
function schoolIcon(): { width: number; height: number; data: Uint8Array } {
  const size = 14
  const data = new Uint8Array(size * size * 4)
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const i = (y * size + x) * 4
      const edge = Math.min(x, y, size - 1 - x, size - 1 - y)
      const corner = Math.min(x, size - 1 - x) + Math.min(y, size - 1 - y)
      if (corner < 2) continue // clipped corners stay transparent
      if (edge < 2) {
        // white border so the square reads on any basemap color
        data[i] = data[i + 1] = data[i + 2] = data[i + 3] = 255
      } else {
        // slate fill #5f6b76
        data[i] = 0x5f
        data[i + 1] = 0x6b
        data[i + 2] = 0x76
        data[i + 3] = 255
      }
    }
  }
  return { width: size, height: size, data }
}

/** Escape text before it goes into popup HTML — data is never trusted markup. */
function esc(value: unknown): string {
  return String(value).replace(
    /[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!,
  )
}

/** Neutral, factual popover copy for a crash point. */
function crashPopupHTML(props: Record<string, unknown>): string {
  const mode =
    props.mode === 'both'
      ? 'people walking and biking'
      : props.mode === 'bike'
        ? 'a person biking'
        : 'a person walking'
  const sev =
    props.sev === 'fatal'
      ? 'A person was killed.'
      : props.sev === 'injury'
        ? 'At least one person was injured.'
        : 'No injuries were recorded.'
  return (
    `<div class="sw-popup"><p class="sw-popup__kicker">Reported crash · ${esc(Number(props.year))}</p>` +
    `<p>Involving ${mode}. ${sev}</p></div>`
  )
}

/**
 * Which crash modes each layer shows, given the mode filter.
 * "both" crashes involve a walker AND a biker, so they appear as a filled
 * dot while walkers are shown, and as a ring when only bikers are shown.
 */
function modeSets(f: Filters): { ped: string[]; bike: string[] } {
  const wantPed = f.modes.includes('ped')
  const wantBike = f.modes.includes('bike')
  return {
    ped: wantPed ? ['ped', 'both'] : [],
    bike: wantBike ? (wantPed ? ['bike'] : ['bike', 'both']) : [],
  }
}

function yearAndMode(f: Filters, modes: string[]): ExpressionSpecification {
  const modeExpr: ExpressionSpecification =
    modes.length === 0
      ? ['boolean', false]
      : ['match', ['get', 'mode'], modes, true, false]
  return [
    'all',
    ['>=', ['get', 'year'], f.yearMin],
    ['<=', ['get', 'year'], f.yearMax],
    modeExpr,
  ]
}

/** Crash size: recedes at county-wide zoom, firms up in a neighborhood. */
function crashRadius(fatalBoost: number, base: [number, number]): ExpressionSpecification {
  const [lo, hi] = base
  return [
    'interpolate',
    ['linear'],
    ['zoom'],
    9,
    ['case', ['==', ['get', 'sev'], 'fatal'], lo + fatalBoost, lo],
    15,
    ['case', ['==', ['get', 'sev'], 'fatal'], hi + fatalBoost, hi],
  ]
}

const CRASH_OPACITY: ExpressionSpecification = [
  'interpolate',
  ['linear'],
  ['zoom'],
  9,
  0.4,
  15,
  0.75,
]

interface Props {
  projects: Project[] // already filtered by district/status
  crashes: CrashCollection | null
  schools: GeoJSON.FeatureCollection | null
  boundary: GeoJSON.FeatureCollection | null
  filters: Filters
  selected: Project | null
  onMapFailed: () => void
}

export default function MapView({
  projects,
  crashes,
  schools,
  boundary,
  filters,
  selected,
  onMapFailed,
}: Props) {
  const containerRef = useRef<HTMLDivElement>(null)
  const mapRef = useRef<MLMap | null>(null)
  const loadedRef = useRef(false)

  // Latest props, reachable from map event handlers without re-binding them.
  const stateRef = useRef({ projects, crashes, schools, boundary, filters, selected })
  stateRef.current = { projects, crashes, schools, boundary, filters, selected }

  /** Push current data + filters into the map. Safe to call repeatedly. */
  function sync(map: MLMap) {
    const { projects, crashes, schools, boundary, filters, selected } = stateRef.current

    const projSrc = map.getSource('projects') as GeoJSONSource | undefined
    if (projSrc) projSrc.setData(projectsToGeoJSON(projects))

    if (boundary && !map.getSource('henrico-boundary')) {
      map.addSource('henrico-boundary', { type: 'geojson', data: boundary })
      const mask = buildMaskGeometry(boundary)
      if (mask) map.addSource('henrico-mask', { type: 'geojson', data: mask as GeoJSON.Feature })
      addBoundaryLayers(map)
    }
    if (crashes && !map.getSource('crashes')) {
      map.addSource('crashes', { type: 'geojson', data: crashes as GeoJSON.FeatureCollection })
      addCrashLayers(map)
    }
    if (schools && !map.getSource('schools')) {
      map.addSource('schools', { type: 'geojson', data: schools })
      addSchoolLayer(map)
    }

    const vis = (on: boolean) => (on ? 'visible' : 'none')
    const projectLayers = [
      'project-sel-line',
      'project-sel-point',
      'project-line-casing',
      'project-line-casing-paper',
      'project-point-casing',
      'project-lines',
      'project-lines-placeholder',
      'project-points',
      'project-points-placeholder',
    ]
    for (const id of projectLayers)
      if (map.getLayer(id)) map.setLayoutProperty(id, 'visibility', vis(filters.layers.projects))
    for (const id of ['crash-fatal-halo', 'crash-ped', 'crash-bike'])
      if (map.getLayer(id)) map.setLayoutProperty(id, 'visibility', vis(filters.layers.crashes))
    if (map.getLayer('schools'))
      map.setLayoutProperty('schools', 'visibility', vis(filters.layers.schools))

    const sets = modeSets(filters)
    if (map.getLayer('crash-ped')) map.setFilter('crash-ped', yearAndMode(filters, sets.ped))
    if (map.getLayer('crash-bike')) map.setFilter('crash-bike', yearAndMode(filters, sets.bike))
    if (map.getLayer('crash-fatal-halo')) {
      const anyShown = [...new Set([...sets.ped, ...sets.bike])]
      map.setFilter('crash-fatal-halo', [
        'all',
        ['==', ['get', 'sev'], 'fatal'],
        yearAndMode(filters, anyShown),
      ])
    }

    const selId = selected?.id ?? ''
    if (map.getLayer('project-sel-line')) map.setFilter('project-sel-line', ['all', ['==', ['geometry-type'], 'LineString'], ['==', ['get', 'id'], selId]])
    if (map.getLayer('project-sel-point')) map.setFilter('project-sel-point', ['all', ['==', ['geometry-type'], 'Point'], ['==', ['get', 'id'], selId]])
  }

  function addBoundaryLayers(map: MLMap) {
    if (map.getSource('henrico-mask')) {
      // Subtle: evaluated by eye, not asserted as "correct" — see MapView's
      // usage notes / the build report for how this was judged.
      addLayerOrdered(map, {
        id: 'henrico-mask-fill',
        type: 'fill',
        source: 'henrico-mask',
        paint: { 'fill-color': COLORS.ink, 'fill-opacity': 0.1 },
      })
    }
    addLayerOrdered(map, {
      id: 'henrico-boundary-line',
      type: 'line',
      source: 'henrico-boundary',
      layout: { 'line-join': 'round' },
      paint: { 'line-color': COLORS.inkSoft, 'line-width': 1.5, 'line-opacity': 0.55 },
    })
  }

  function addProjectLayers(map: MLMap) {
    map.addSource('projects', {
      type: 'geojson',
      data: projectsToGeoJSON(stateRef.current.projects),
    })

    // ink halo under the selected project — reads as "this one is chosen"
    addLayerOrdered(map, {
      id: 'project-sel-line',
      type: 'line',
      source: 'projects',
      filter: ['==', ['get', 'id'], ''],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: { 'line-color': COLORS.ink, 'line-width': 16, 'line-opacity': 0.9 },
    })
    addLayerOrdered(map, {
      id: 'project-sel-point',
      type: 'circle',
      source: 'projects',
      filter: ['==', ['get', 'id'], ''],
      paint: { 'circle-radius': 18, 'circle-color': COLORS.ink, 'circle-opacity': 0.9 },
    })

    // Casing stack for EVERY project line: ink (holds status colors to 3:1+
    // contrast on the light basemap) under paper (cuts a clean channel
    // through basemap clutter so the color reads as the subject, not
    // fighting with roads/labels underneath it).
    addLayerOrdered(map, {
      id: 'project-line-casing',
      type: 'line',
      source: 'projects',
      filter: ['==', ['geometry-type'], 'LineString'],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: { 'line-color': COLORS.ink, 'line-width': 10, 'line-opacity': 0.85 },
    })
    addLayerOrdered(map, {
      id: 'project-line-casing-paper',
      type: 'line',
      source: 'projects',
      filter: ['==', ['geometry-type'], 'LineString'],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: { 'line-color': COLORS.paper, 'line-width': 8, 'line-opacity': 0.95 },
    })
    addLayerOrdered(map, {
      id: 'project-point-casing',
      type: 'circle',
      source: 'projects',
      filter: ['==', ['geometry-type'], 'Point'],
      paint: { 'circle-radius': 12, 'circle-color': COLORS.paper, 'circle-opacity': 0.95 },
    })

    // real projects: solid line — placeholders: dashed (dasharray can't be
    // data-driven in MapLibre, hence two layers)
    addLayerOrdered(map, {
      id: 'project-lines',
      type: 'line',
      source: 'projects',
      filter: ['all', ['==', ['geometry-type'], 'LineString'], ['!=', ['get', 'placeholder'], true]],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: { 'line-color': STATUS_COLOR, 'line-width': 6 },
    })
    addLayerOrdered(map, {
      id: 'project-lines-placeholder',
      type: 'line',
      source: 'projects',
      filter: ['all', ['==', ['geometry-type'], 'LineString'], ['==', ['get', 'placeholder'], true]],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: { 'line-color': STATUS_COLOR, 'line-width': 6, 'line-dasharray': [1.8, 1.4] },
    })

    // verified points: solid status fill with an ink edge (contrast + "real")
    addLayerOrdered(map, {
      id: 'project-points',
      type: 'circle',
      source: 'projects',
      filter: ['all', ['==', ['geometry-type'], 'Point'], ['!=', ['get', 'placeholder'], true]],
      paint: {
        'circle-radius': 9,
        'circle-color': STATUS_COLOR,
        'circle-stroke-color': COLORS.ink,
        'circle-stroke-width': 2,
      },
    })
    // placeholder points: hollow ring — provisional, never mistaken for real,
    // mirroring the dashed treatment of placeholder lines
    addLayerOrdered(map, {
      id: 'project-points-placeholder',
      type: 'circle',
      source: 'projects',
      filter: ['all', ['==', ['geometry-type'], 'Point'], ['==', ['get', 'placeholder'], true]],
      paint: {
        'circle-radius': 9,
        'circle-color': COLORS.paper,
        'circle-stroke-color': STATUS_COLOR,
        'circle-stroke-width': 3,
      },
    })
  }

  function addCrashLayers(map: MLMap) {
    // dark outline that marks fatal crashes, drawn under the dot itself.
    // Sized/opacity recede at county-wide zoom, firm up in a neighborhood —
    // crashes are context here, not the subject; see MapView's file header.
    addLayerOrdered(map, {
      id: 'crash-fatal-halo',
      type: 'circle',
      source: 'crashes',
      filter: ['==', ['get', 'sev'], 'fatal'],
      paint: {
        'circle-radius': ['interpolate', ['linear'], ['zoom'], 9, 5.5, 15, 9],
        'circle-color': 'rgba(0,0,0,0)',
        'circle-stroke-color': COLORS.ink,
        'circle-stroke-width': ['interpolate', ['linear'], ['zoom'], 9, 1.2, 15, 2],
        'circle-stroke-opacity': ['interpolate', ['linear'], ['zoom'], 9, 0.45, 15, 0.85],
      },
    })
    addLayerOrdered(map, {
      id: 'crash-ped',
      type: 'circle',
      source: 'crashes',
      filter: ['match', ['get', 'mode'], ['ped', 'both'], true, false],
      paint: {
        'circle-radius': crashRadius(2, [2.5, 4.5]),
        'circle-color': COLORS.crash,
        'circle-opacity': CRASH_OPACITY,
        'circle-stroke-color': '#ffffff',
        'circle-stroke-width': 1,
        'circle-stroke-opacity': CRASH_OPACITY,
      },
    })
    addLayerOrdered(map, {
      id: 'crash-bike',
      type: 'circle',
      source: 'crashes',
      filter: ['match', ['get', 'mode'], ['bike'], true, false],
      paint: {
        // a ring: transparent center, red stroke
        'circle-radius': crashRadius(1.5, [2.5, 4.5]),
        'circle-color': 'rgba(0,0,0,0)',
        'circle-stroke-color': COLORS.crash,
        'circle-stroke-width': ['interpolate', ['linear'], ['zoom'], 9, 1.4, 15, 2.2],
        'circle-stroke-opacity': CRASH_OPACITY,
      },
    })
  }

  function addSchoolLayer(map: MLMap) {
    if (!map.hasImage('school-square')) map.addImage('school-square', schoolIcon())
    addLayerOrdered(map, {
      id: 'schools',
      type: 'symbol',
      source: 'schools',
      layout: { 'icon-image': 'school-square', 'icon-size': 1, 'icon-allow-overlap': true },
    })
  }

  // ----- map lifecycle (once) -----
  useEffect(() => {
    if (!containerRef.current || mapRef.current) return

    // Opt-in only: enables reading the WebGL drawing buffer for
    // scripts/verify-map.mjs. Off for every real visitor (small perf cost),
    // on only when that script navigates with ?verifyMap=1.
    const verifyMap =
      typeof window !== 'undefined' && new URLSearchParams(window.location.search).get('verifyMap') === '1'

    let map: MLMap
    try {
      map = new maplibregl.Map({
        container: containerRef.current,
        style: STYLE_URL,
        bounds: COUNTY_BOUNDS,
        fitBoundsOptions: { padding: 24 },
        maxBounds: paddedMaxBounds(),
        attributionControl: { compact: false },
        ...(verifyMap ? { canvasContextAttributes: { preserveDrawingBuffer: true } } : {}),
      })
    } catch {
      onMapFailed()
      return
    }
    mapRef.current = map
    if (import.meta.env.DEV) {
      // dev-only handle for debugging in the browser console
      ;(window as unknown as Record<string, unknown>).__swMap = map
    }

    map.addControl(new maplibregl.NavigationControl({ showCompass: false }), 'bottom-right')
    // The canvas is keyboard-focusable and pannable. We describe it as a
    // complementary view and tell keyboard users how to inspect a feature —
    // projects are also fully reachable through the accessible project list.
    map
      .getCanvas()
      .setAttribute(
        'aria-label',
        'Map of pedestrian-safety projects and crashes in Henrico County. ' +
          'Pan with the arrow keys; press Enter to inspect the feature at the center crosshair. ' +
          'All projects are also listed in the project list.',
      )
    map.getCanvas().setAttribute('role', 'application')

    // Center crosshair: the keyboard "cursor". Shown ONLY when the canvas has
    // real keyboard focus (:focus-visible) — NOT on a mouse click, which
    // MapLibre also focuses the canvas for (to enable keyboard nav right
    // after a click). Checking :focus-visible inside the 'focus' handler
    // uses the browser's own keyboard-vs-pointer heuristic instead of a
    // hand-rolled one, so it stays correct across input methods.
    const crosshair = document.createElement('div')
    crosshair.className = 'map-crosshair'
    crosshair.setAttribute('aria-hidden', 'true')
    map.getContainer().appendChild(crosshair)
    const canvas = map.getCanvas()
    canvas.addEventListener('focus', () => {
      if (canvas.matches(':focus-visible')) crosshair.classList.add('map-crosshair--on')
    })
    canvas.addEventListener('blur', () => crosshair.classList.remove('map-crosshair--on'))

    // ---- Layers: (re)installed for whichever basemap style is active.
    // setStyle() (the fallback path) wipes custom sources/layers, so this must
    // be safe to run again after a style swap; the getSource guard makes it
    // idempotent within a single style.
    const installLayers = (m: MLMap) => {
      if (m.getSource('projects')) return
      addProjectLayers(m)
      sync(m)
    }

    // ---- Interactions: bound to the map, not the style, so attach once.
    // Casing layers are included so the effective click/tap target is wider
    // than just the narrow color line/point — useful on mobile.
    const interactive = [
      'project-lines',
      'project-lines-placeholder',
      'project-line-casing-paper',
      'project-points',
      'project-points-placeholder',
      'project-point-casing',
      'crash-ped',
      'crash-bike',
      'schools',
    ]
    for (const layer of interactive) {
      map.on('mouseenter', layer, () => (map.getCanvas().style.cursor = 'pointer'))
      map.on('mouseleave', layer, () => (map.getCanvas().style.cursor = ''))
    }

    /**
     * Act on a feature: navigate for a project, or open a popup for a
     * crash/school. `moveFocus` is set for keyboard activation so the popup
     * receives focus (screen-reader users hear it; Escape/Tab work).
     */
    const activateFeature = (
      f: maplibregl.MapGeoJSONFeature,
      lngLat: maplibregl.LngLatLike,
      moveFocus: boolean,
    ) => {
      if (f.layer.id.startsWith('project-')) {
        navigate(`/project/${f.properties.id}`)
        return
      }
      const popup = new maplibregl.Popup({
        offset: f.layer.id === 'schools' ? 10 : 8,
        closeButton: f.layer.id !== 'schools',
        focusAfterOpen: moveFocus,
      }).setLngLat(lngLat)
      popup.setHTML(
        f.layer.id === 'schools'
          ? `<div class="sw-popup"><p class="sw-popup__kicker">School</p><p>${esc(f.properties.name)}</p></div>`
          : crashPopupHTML(f.properties),
      )
      popup.addTo(map)
    }

    const present = () => interactive.filter((l) => map.getLayer(l))

    map.on('click', (e: MapMouseEvent) => {
      const f = map.queryRenderedFeatures(e.point, { layers: present() })[0]
      if (f) activateFeature(f, e.lngLat, false)
    })

    // Keyboard activation: Enter/Space inspects the feature nearest the map
    // center (marked by the crosshair that appears when the canvas is focused).
    map.getCanvas().addEventListener('keydown', (ev: KeyboardEvent) => {
      if (ev.key !== 'Enter' && ev.key !== ' ') return
      const rect = map.getContainer().getBoundingClientRect()
      const cx = rect.width / 2
      const cy = rect.height / 2
      // search a small box so features don't need pixel-perfect aim
      const box: [maplibregl.PointLike, maplibregl.PointLike] = [
        [cx - 16, cy - 16],
        [cx + 16, cy + 16],
      ]
      const f = map.queryRenderedFeatures(box, { layers: present() })[0]
      if (!f) return
      ev.preventDefault()
      // anchor the popup at the map center (where the crosshair sits)
      activateFeature(f, map.getCenter(), true)
    })

    // ---- Basemap resilience. The map must never sit as a silent blank: if the
    // primary style never loads, retry once with the free demotiles style; if
    // that also fails, surface the on-voice fallback panel (onMapFailed). Data
    // layers are re-installed over whichever style ends up loading.
    let styleState: 'primary' | 'fallback' | 'failed' = 'primary'
    const alive = () => mapRef.current === map // guard stale timers after unmount

    const markLoaded = () => {
      loadedRef.current = true
      installLayers(map)
    }
    const giveUp = (reason: string) => {
      if (styleState === 'failed' || !alive()) return
      styleState = 'failed'
      console.error('[SafeWalk] Basemap unavailable:', reason)
      onMapFailed()
    }
    const goFallback = (reason: string) => {
      if (styleState !== 'primary' || !alive()) return
      styleState = 'fallback'
      console.warn('[SafeWalk] Primary basemap failed, retrying with fallback:', reason)
      map.once('style.load', markLoaded)
      window.setTimeout(() => {
        if (alive() && styleState === 'fallback' && !map.isStyleLoaded()) giveUp('fallback timeout')
      }, 8000)
      try {
        map.setStyle(FALLBACK_STYLE)
      } catch (err) {
        giveUp(String(err))
      }
    }

    map.on('load', () => {
      if (styleState === 'primary') markLoaded()
    })
    map.on('error', (e) => {
      // Only errors BEFORE a style has loaded mean "no basemap". Once a style
      // is up, stray tile errors are harmless and must not trigger a failover.
      if (alive() && !map.isStyleLoaded()) goFallback(String(e?.error?.message ?? 'map error'))
    })
    // Watchdog: some failures (DNS, hang) never emit an error event.
    window.setTimeout(() => {
      if (alive() && styleState === 'primary' && !map.isStyleLoaded()) goFallback('primary timeout')
    }, 8000)

    return () => {
      // map.remove() tears down MapLibre's own DOM (canvas, controls) but not
      // elements we appended ourselves — without this, React StrictMode's
      // dev-only double-invoke of this effect leaves an orphaned crosshair
      // <div> behind on every mount (harmless in production, where effects
      // run once, but real DOM debt in dev regardless).
      crosshair.remove()
      map.remove()
      mapRef.current = null
      loadedRef.current = false
    }
    // The map is created exactly once; prop changes flow through sync().
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // ----- react to data / filter changes -----
  useEffect(() => {
    const map = mapRef.current
    if (map && loadedRef.current) sync(map)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projects, crashes, schools, boundary, filters, selected])

  // ----- auto-zoom to the selected project -----
  useEffect(() => {
    const map = mapRef.current
    if (!map || !selected) return
    const pts = geometryPoints(selected)
    const desktop = window.matchMedia('(min-width: 760px)').matches
    const padding = desktop
      ? { top: 80, left: 80, bottom: 80, right: 460 } // clear the detail panel
      : { top: 60, left: 40, right: 40, bottom: Math.round(window.innerHeight * 0.55) }
    if (pts.length === 1) {
      map.easeTo({ center: pts[0], zoom: Math.max(map.getZoom(), 14), padding, duration: 500 })
    } else {
      const bounds = pts.reduce((b, p) => b.extend(p), new maplibregl.LngLatBounds(pts[0], pts[0]))
      map.fitBounds(bounds, { padding, maxZoom: 15, duration: 500 })
    }
  }, [selected])

  return <div ref={containerRef} className="map-canvas" data-testid="map" />
}
